[package]
name = "rustic-sqlite-store"
version = "0.1.0"
authors = ["Max Jöhnk <maxjoehnk@gmail.com>"]

[dependencies]
diesel = { version = "1.0.0", features = ["sqlite"] }

[dependencies.rustic-core]
git = "https://github.com/rustic-music-player/core"
